# Generated by Django 5.2.1 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_brand_logo_url_alter_car_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='year_from',
            field=models.PositiveIntegerField(default=2000, help_text='First model year this car was sold (e.g. 2006).'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, help_text='Last model year (e.g. 2020 if discontinued). Leave empty if still on sale.', null=True),
        ),
    ]
