# Generated by Django 5.2.1 on 2026-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_cars_car_status_featured_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sell_inquiry_seen',
            field=models.BooleanField(default=False, help_text='Staff has opened Sell car inquiries; used for sidebar badge.'),
        ),
        migrations.AddField(
            model_name='car',
            name='submit_via_sell_form',
            field=models.BooleanField(default=False),
        ),
    ]
