# Generated by Django 5.2.1 on 2026-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_sell_form_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
