# Generated by Django 5.2.1 on 2026-04-01 12:18

from django.db import migrations, models
from django.db.models import F


def backfill_listed_at(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    Car.objects.filter(listed_at__isnull=True, status='APPROVED').update(listed_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_add_car_status_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='listed_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='When the car was first approved / listed (set automatically; not shown on the public site).', null=True),
        ),
        migrations.RunPython(backfill_listed_at, migrations.RunPython.noop),
    ]
