# Generated by Django 5.2.1 on 2026-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_listed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
