# Generated by Django 5.2.1 on 2026-05-14 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_car_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Staff reason when a sell-form listing is rejected.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional manufacturing month (stored as 1–12). Choose Jan–Dec in forms; customers see e.g. Jan 2021.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
